# Generated by Django 3.1.6 on 2021-02-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.pharmacy')),
            ],
        ),
    ]
