# Generated by Django 3.1.7 on 2021-02-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
    ]
