# Generated by Django 3.1.6 on 2021-02-17 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
