# Generated by Django 3.1.7 on 2021-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_drug_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='drug',
            name='pharmacy',
            field=models.ManyToManyField(to='health.Pharmacy'),
        ),
    ]
