# Generated by Django 3.1.7 on 2021-02-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='located_at',
            field=models.OneToOneField(default='1', unique=False,on_delete=django.db.models.deletion.CASCADE, to='health.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.location'),
        ),
    ]
