# Generated by Django 3.1.7 on 2021-02-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20210222_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='located_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
