# Generated by Django 3.1.7 on 2021-02-22 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_drug_location_pharmacy_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='directtion',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
