# Generated by Django 3.1.7 on 2021-02-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_pharmacy_directtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='directtion',
            new_name='direction',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='health.location'),
        ),
    ]
