# Generated by Django 3.1.7 on 2021-02-23 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_auto_20210223_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.insurance'),
            preserve_default=False,
        ),
    ]
