# Generated by Django 3.1.7 on 2021-02-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20210223_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.insurance'),
        ),
    ]
