# Generated by Django 3.1.7 on 2021-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_auto_20210223_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='insurance',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='insurance',
            field=models.ManyToManyField(to='health.Insurance'),
        ),
    ]
