# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_auto_20210223_1158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
